### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by natalifm** [natalifm/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Natalifm998** [comment]
**LANGUAGES**
🇺🇸 ENGLISH 🇷🇺 РУССКИЙ

**Comment by Natalifm998** [comment]
**SKILLS**
NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING

**Comment by Natalifm998** [comment]
**CHARACTER**
ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING

**Comment by Natalifm998** [comment]
**LIKES**😃
[BILLIONS](https://www.youtube.com/watch?v=u_aLESDql1U) FILET-O-FISH BIG MAC [CHINA ](https://www.youtube.com/watch?v=u_aLESDql1U)QUARTER POUNDER DIET COKE TARIFFS BIBLE ARTOF DEAL PATRIOTS BEAUTIFUL MODELS GOLD REAL ESTATE WAR PROTESTERS CONSTRUCTION RUSSIANS BANKS SPORTS WOMEN MEXICO RED HAT KOREANS GOLF EVERYBODY [[1]](https://www.youtube.com/watch?v=0f9ysmciWUk) [[2]](https://www.youtube.com/watch?v=TTdmKaXAfAs)

**Comment by Natalifm998** [comment]
**DISLIKES**😞
DOGS MEDIA CNN GERMANS MEXICANS IMMIGRANTS SHITHOLE COUNTRIES UNATTRACTIVE WOMEN BLACKS SUSHI HOT-DOGS ALCOHOL FRUIT CHRISTMAS PARTIES LIBERALS

**Comment by Natalifm998** [comment]
**WANTS**😎
BE HEALTHY GROW A TREE BUILD TRUMP AIRPORT HAVE A TASTE DO A HARLEM SHAKE IN CONGRESS TO GOLF MORE OFTEN WIN ALL THE COURT SUITS

**Comment by Natalifm998** [comment]
**EDUCATION**

- 2011 - Asked friends who are prominent and wealthy alumni of the New York Military Academy to secure my academic records so they could not be seen by anyone, never!
- 1996 - Transferred to the Wharton School of the University of Pennsylvania and graduated in May 1968 with a B.S. in economics
- 1964 - Started studying in Fordham University
- 1959 - Enrolled in the New York Military Academy, a private boarding school, after my parents discovered I made frequent trips into Manhattan without their permission
